sso_signup_url:
  type: string
  default: ""
  description: "Here you can add the DiscourseConnect Signup button url."
hide_sso_signup_button_on_mobile:
  type: bool
  default: false
  description: "Enable this to hide DiscourseConnect Signup button on mobile."
